import { OpenAPIHono, createRoute, z } from "@hono/zod-openapi";
import { HTTPException } from "hono/http-exception";
import { describe, expect, it } from "vitest";

import { createApp } from "./app";

describe("api", () => {
  it("answers the liveness probe", async () => {
    const res = await createApp().request("/health");
    expect(res.status).toBe(200);
    await expect(res.json()).resolves.toMatchObject({ status: "ok", service: "sw-api" });
  });
});

describe("openapi document", () => {
  it("is served when exposed", async () => {
    // @sw/api-client is generated from this. If the document stops being emitted, the
    // client silently goes stale rather than failing loudly, so it gets a test.
    const res = await createApp({ exposeOpenApiDoc: true }).request("/openapi.json");
    expect(res.status).toBe(200);
    const doc = (await res.json()) as { openapi: string; paths: Record<string, unknown> };
    expect(doc.openapi).toBe("3.1.0");
    expect(doc.paths).toHaveProperty("/health");
  });

  it("emits genuine 3.1 schemas, not 3.0 schemas wearing a 3.1 label", async () => {
    // The assertion that matters, and the one this file used to be missing.
    //
    // Asserting `doc.openapi === "3.1.0"` (above) reads back the literal string we passed
    // into the config — it cannot fail, and it passed happily while the document was
    // being generated by `doc()`, the OpenAPI *3.0* generator. The difference only shows
    // up in the schemas: 3.0 spells a nullable field `nullable: true`, 3.1 spells it
    // `type: ["string", "null"]`. `nullable` is not a keyword in 3.1, so a generator
    // reading the document at its declared version drops it and types the field as
    // non-nullable — a generated client that disagrees with the server.
    //
    // Nothing in the health schema is nullable, which is why this went unnoticed. Rather
    // than wait for an entity schema to expose it, build a throwaway app with a nullable
    // field and assert on the generated shape directly.
    const schema = z.object({ note: z.string().nullable() }).openapi("Probe");
    const route = createRoute({
      method: "get",
      path: "/probe",
      responses: {
        200: { content: { "application/json": { schema } }, description: "probe" },
      },
    });

    const probe = new OpenAPIHono();
    probe.openapi(route, (c) => c.json({ note: null }, 200));
    probe.doc31("/openapi.json", { openapi: "3.1.0", info: { title: "probe", version: "0" } });

    const doc = (await (await probe.request("/openapi.json")).json()) as {
      components: { schemas: { Probe: { properties: { note: Record<string, unknown> } } } };
    };
    const note = doc.components.schemas.Probe.properties.note;

    expect(note["type"]).toEqual(["string", "null"]);
    expect(note).not.toHaveProperty("nullable");
  });

  it("is withheld in production", async () => {
    // The spec enumerates every entity type and field name, including DM-tier field
    // names — the visibility filter strips those fields from responses, but the schema
    // still describes them. See docs/adr/0003-standalone-http-api.md.
    const res = await createApp({ exposeOpenApiDoc: false }).request("/openapi.json");
    expect(res.status).toBe(404);
  });
});

describe("error handling", () => {
  it("returns a JSON 404 for an unknown route", async () => {
    const res = await createApp().request("/no-such-route");
    expect(res.status).toBe(404);
    await expect(res.json()).resolves.toEqual({ error: "Not found" });
  });

  it("does not leak internals when a handler throws", async () => {
    const app = createApp();
    app.get("/boom", () => {
      throw new Error("SELECT secret_allegiance FROM npc WHERE id = 42");
    });

    const res = await app.request("/boom");
    expect(res.status).toBe(500);

    const body = await res.text();
    expect(body).toBe(JSON.stringify({ error: "Internal server error" }));
    // The specific thing being guarded: an error body echoing a query, a table name or a
    // stack frame is a disclosure on a service whose whole premise is hiding content.
    expect(body).not.toContain("secret_allegiance");
    expect(body).not.toContain("SELECT");
  });

  it("passes through a deliberate HTTPException message", async () => {
    const app = createApp();
    app.get("/nope", () => {
      throw new HTTPException(403, { message: "Insufficient clearance" });
    });

    const res = await app.request("/nope");
    expect(res.status).toBe(403);
    await expect(res.json()).resolves.toEqual({ error: "Insufficient clearance" });
  });
});
